ALTER TABLE runs ADD COLUMN admitted_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN ended_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN duration_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN duration_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN terminal_reason TEXT NOT NULL DEFAULT '';
