#!/usr/bin/env bash
# Render the Homebrew formula for a published release (design D24, §13) from
# its checksums.txt, on stdout. The tap workflow runs it; so can you, to look.
#
#   scripts/homebrew-formula.sh <tag> <checksums.txt>
#
# A formula, not a cask: Homebrew does not quarantine a formula's download. It
# installs the macOS whr and, from the same archive (#489), the linux/arm64
# guest binaries in libexec/whr (where
# whr serve looks for them, next to the resolved binary) and the completions.
set -euo pipefail

repo="${WHR_RELEASE_REPO:-wstein/workharbor}"
tag="${1:-}"
sums="${2:-}"

die() {
  echo "homebrew-formula: $*" >&2
  exit 1
}

[[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "usage: $0 vX.Y.Z checksums.txt (a release, not a prerelease; got '$tag')"
[ -f "$sums" ] || die "no checksums file '$sums'"

version="${tag#v}"
base="https://github.com/$repo/releases/download/$tag"
mac="whr_${version}_darwin_arm64.tar.gz"

sha() {
  local h
  h="$(awk -v f="$1" '$2 == f { print $1 }' "$sums")"
  [[ "$h" =~ ^[0-9a-f]{64}$ ]] || die "checksums.txt has no single sha256 for $1"
  echo "$h"
}
mac_sha="$(sha "$mac")"

cat <<FORMULA
# Generated by scripts/homebrew-formula.sh in $repo for $tag. Do not edit:
# the next published release replaces it.
class Whr < Formula
  desc "Supervise AI coding agents in isolated workspaces, with a human in the loop"
  homepage "https://github.com/$repo"
  url "$base/$mac"
  sha256 "$mac_sha"
  version "$version"
  license "EUPL-1.2"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "bin/whr"
    (libexec/"whr").install "guest/whr-shim-linux-arm64", "guest/whr-proxy-linux-arm64"
    generate_completions_from_executable(bin/"whr", "completion")
  end

  def caveats
    <<~EOS
      The guest binaries are in #{opt_libexec}/whr. Fill the tool store with:
        whr tools build -store <tool store> -shim #{opt_libexec}/whr/whr-shim-linux-arm64
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whr version")
  end
end
FORMULA
